/*
 * This code is automatically generated by freq_table.rb.
 */
#ifndef FREQ_TABLE_H
#define FREQ_TABLE_H

#ifdef __cplusplus
extern "C" {
#endif

extern const float freq_table[128];
extern const int key_C0;
extern const int key_Cp0;
extern const int key_D0;
extern const int key_Dp0;
extern const int key_E0;
extern const int key_F0;
extern const int key_Fp0;
extern const int key_G0;
extern const int key_Gp0;
extern const int key_A0;
extern const int key_Ap0;
extern const int key_B0;
extern const int key_C1;
extern const int key_Cp1;
extern const int key_D1;
extern const int key_Dp1;
extern const int key_E1;
extern const int key_F1;
extern const int key_Fp1;
extern const int key_G1;
extern const int key_Gp1;
extern const int key_A1;
extern const int key_Ap1;
extern const int key_B1;
extern const int key_C2;
extern const int key_Cp2;
extern const int key_D2;
extern const int key_Dp2;
extern const int key_E2;
extern const int key_F2;
extern const int key_Fp2;
extern const int key_G2;
extern const int key_Gp2;
extern const int key_A2;
extern const int key_Ap2;
extern const int key_B2;
extern const int key_C3;
extern const int key_Cp3;
extern const int key_D3;
extern const int key_Dp3;
extern const int key_E3;
extern const int key_F3;
extern const int key_Fp3;
extern const int key_G3;
extern const int key_Gp3;
extern const int key_A3;
extern const int key_Ap3;
extern const int key_B3;
extern const int key_C4;
extern const int key_Cp4;
extern const int key_D4;
extern const int key_Dp4;
extern const int key_E4;
extern const int key_F4;
extern const int key_Fp4;
extern const int key_G4;
extern const int key_Gp4;
extern const int key_A4;
extern const int key_Ap4;
extern const int key_B4;
extern const int key_C5;
extern const int key_Cp5;
extern const int key_D5;
extern const int key_Dp5;
extern const int key_E5;
extern const int key_F5;
extern const int key_Fp5;
extern const int key_G5;
extern const int key_Gp5;
extern const int key_A5;
extern const int key_Ap5;
extern const int key_B5;
extern const int key_C6;
extern const int key_Cp6;
extern const int key_D6;
extern const int key_Dp6;
extern const int key_E6;
extern const int key_F6;
extern const int key_Fp6;
extern const int key_G6;
extern const int key_Gp6;
extern const int key_A6;
extern const int key_Ap6;
extern const int key_B6;
extern const int key_C7;
extern const int key_Cp7;
extern const int key_D7;
extern const int key_Dp7;
extern const int key_E7;
extern const int key_F7;
extern const int key_Fp7;
extern const int key_G7;
extern const int key_Gp7;
extern const int key_A7;
extern const int key_Ap7;
extern const int key_B7;
extern const int key_C8;
extern const int key_Cp8;
extern const int key_D8;
extern const int key_Dp8;
extern const int key_E8;
extern const int key_F8;
extern const int key_Fp8;
extern const int key_G8;
extern const int key_Gp8;
extern const int key_A8;
extern const int key_Ap8;
extern const int key_B8;
extern const int key_C9;
extern const int key_Cp9;
extern const int key_D9;
extern const int key_Dp9;
extern const int key_E9;
extern const int key_F9;
extern const int key_Fp9;
extern const int key_G9;
extern const int key_Gp9;
extern const int key_A9;
extern const int key_Ap9;
extern const int key_B9;
extern const int key_C10;
extern const int key_Cp10;
extern const int key_D10;
extern const int key_Dp10;
extern const int key_E10;
extern const int key_F10;
extern const int key_Fp10;
extern const int key_G10;
#ifdef __cplusplus
}
#endif

#endif
